### ISSUE TITLE
server → serve (in the README)

### ISSUE THREAD

**Issue by elia** [callumacrae/baconjs#1]
:frog:

**Comment by callumacrae** [comment]
Wait, people look at this library?! :D

**Comment by elia** [comment]
Not really, I'm just a random readme-grammar-nazi. We browse every readme on earth in order to catch silly errors. 

(@sa_su_ke pointed me at this project in order to bring something similar to [opal](/opal/opal) :frog:)

**Comment by callumacrae** [comment]
I forgot what this project actually does :smile: I have fixed the typo, though.

**Comment by elia** [comment]
:smiley:
